# Generated by Django 5.1.6 on 2025-06-20 14:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskapp', '0002_escalationnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalationnote',
            name='author',
        ),
        migrations.AddField(
            model_name='escalationnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escalationnote',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
