# Generated by Django 5.1.6 on 2025-06-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskapp', '0003_remove_escalationnote_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabrequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='cab_attachments/'),
        ),
    ]
